FROM php:8.1-apache

COPY ./web /var/www/html

EXPOSE 7077

RUN docker-php-ext-install pdo_mysql

RUN chown -R www-data:www-data /var/www/html \
  && chmod -R 744 /var/www/html \
  && find /var/www/html -type d -exec chmod g+s {} \;